dist: xenial
language: python
env:
  - TWILIO_AUTH_TOKEN=1
  - TWILIO_ACCOUNT_SID=1
python:
  - "3.7"
  - "nightly"
services:
  - postgresql
install:
  - pip install -r requirements.txt
script:
  - python ./manage.py test
